runtime: python310  
entrypoint:  gunicorn -b :$PORT app:app #gunicorn -k eventlet -w 1 app:app  

env_variables:  
  GOOGLE_APPLICATION_CREDENTIALS: "google-credentials.json"  

handlers:  
- url: /static  
  static_files: templates/index.html  
  upload: templates/index.html  

- url: /.*  
  script: auto  
